### PR TITLE
Feature: Editorial workflow

### LINKED ISSUE #18: Approval of content
AS A PD Director
I WANT to be able to approve the final content
SO THAT the content creation process is smoother

**Acceptance criteria**
**Scenario: approval of blocks**
GIVEN a new block was created by a PD volunteer
WHEN the person with the "approval" role is happy with it
THEN they can publish the block.

### PR DESCRIPTION
**Pull request by SallyMcGrath**
https://decapcms.org/docs/configuration-options/#publish-mode
https://cms-demo.netlify.com/#/workflow

Turns on the editorial kanban, where you can review and promote PRs using a GUI.

Fixes #18

### CODE REVIEW

**Comment by SallyMcGrath** [comment]
Reminding you about this, @kfklein15

**Comment by kfklein15** [comment]
I believe @LaraHuzjan replied to you on this. But not 100% sure, so tagging her.

**Comment by SallyMcGrath** [comment]
> I believe @LaraHuzjan replied to you on this. But not 100% sure, so tagging her.

There's nothing on this PR from Lara

**Comment by kfklein15** [comment]
Not on this PR, but I think she replied in other ways :) That's why I am tagging her so she can see it.

**Comment by LaraHuzjan** [comment]
@SallyMcGrath @kfklein15 
This is what I wrote: 

Thank you for this Sally, just some comments for Karen and you to see:
-we still keep the Word document as it's easier to comment and imo is more clear
-the person that makes the content uploads the content (preferably in a week's time)
-can we omit the "draft" part and just have "in review" (once uploaded by the content creator it's already in review) and "ready" (once one of us has reviewed it and if necessary made any changes)

**Comment by SallyMcGrath** [comment]
> @SallyMcGrath @kfklein15 This is what I wrote:
> 
> Thank you for this Sally, just some comments for Karen and you to see: -we still keep the Word document as it's easier to comment and imo is more clear -the person that makes the content uploads the content (preferably in a week's time) -can we omit the "draft" part and just have "in review" (once uploaded by the content creator it's already in review) and "ready" (once one of us has reviewed it and if necessary made any changes)

Thanks Lara

Can I ask you to more clearly state what changes (if any) you require on this PR? There's no Word document here, for example.

**Comment by LaraHuzjan** [comment]
@SallyMcGrath 
First two are more meant for Karen, but the last comment is meant for this - https://cms-demo.netlify.com/#/workflow

**Comment by SallyMcGrath** [comment]
This will likely stay blocked until someone spends some time understanding and explaining clearly exactly what they need.

**Pull request merged**
