### PR TITLE
Mount main curriculum theme to PD

### PR DESCRIPTION
**Pull request by SallyMcGrath**
This will show PD vols the layout of the curriculum.

There's a larger piece of work to do if we really want this, as the main theme expects linked blocks for PD, and we'd need to fix up the menus a bit, turn on search, etc. But here's a simple prototype to look at to see if we want this at all.

### CODE REVIEW

**Comment by kfklein15** [comment]
Thaks, Sally. To confirm, it's just the first-page layout that has changed, nothing else, correct?
The tests are failing. Should I approve it anyway?

**Comment by SallyMcGrath** [comment]
This changes the layout to show you what the PD block would look like in the main curriculum. As with all these previews, if you try to navigate by clicking links it will navigate out of the branch preview to the deployed site. You can get back to the preview version of any page by prepending `deploy-preview-52-` to the url. 

Here are some direct links to example views:

Module / sprint view

https://deploy-preview-52--cyf-pd.netlify.app/modules/fundamentals/

block view

https://deploy-preview-52--cyf-pd.netlify.app/blocks/presenting-your-blockly-project/readme/

Daniel asked me if this was possible so I made this for you and your team to explore and think if it's helpful.

**Comment by kfklein15** [comment]
It does look much nicer and makes sense, especially the module view (
https://deploy-preview-52--cyf-pd.netlify.app/modules/fundamentals/)
But I also don't think this falls in the category of urgent, albeit
important.

**Comment by SallyMcGrath** [comment]
> It does look much nicer and makes sense, especially the module view ( https://deploy-preview-52--cyf-pd.netlify.app/modules/fundamentals/) But I also don't think this falls in the category of urgent, albeit important.

It's not marked as urgent. Can you explain why you have said this?

**Comment by kfklein15** [comment]
Because I don't think it is something urgent to do.

**Comment by SallyMcGrath** [comment]
feels like this is stale

**Pull request closed without merging**
